# Generated by Django 2.2.17 on 2020-12-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201227_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='image2',
            new_name='image',
        ),
    ]
