# Generated by Django 2.2.17 on 2020-12-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201227_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
